#pragma once

int CNT_CALL_GET_LEFT_USER = 0;
int CNT_CALL_GET_RIGHT_USER = 0;

int CNT_CALL_CHANGE_INTERVAL_LEN = 0;

int CNT_CALL_ADD_USER_IN_INTERVAL = 0;
int CNT_CALL_REMOVE_USER_IN_INTERVAL = 0;

int CNT_CALL_INTERVAL_FLOW_OVER = 0;
int CNT_ACCEPTED_INTERVAL_FLOW_OVER = 0;
int CNT_CALL_INTERVAL_INCREASE_LEN = 0;
int CNT_ACCEPTED_INTERVAL_INCREASE_LEN = 0;
int CNT_CALL_INTERVAL_DECREASE_LEN = 0;
int CNT_ACCEPTED_INTERVAL_DECREASE_LEN = 0;
int CNT_CALL_INTERVAL_GET_FULL_FREE_SPACE = 0;
int CNT_ACCEPTED_INTERVAL_GET_FULL_FREE_SPACE = 0;
int CNT_CALL_INTERVAL_DO_MERGE_EQUAL = 0;
int CNT_CALL_INTERVAL_DO_SPLIT = 0;
int CNT_CALL_INTERVAL_MERGE_EQUAL = 0;
int CNT_ACCEPTED_INTERVAL_MERGE_EQUAL = 0;
int CNT_CALL_INTERVAL_SPLIT = 0;
int CNT_ACCEPTED_INTERVAL_SPLIT = 0;

int CNT_CALL_USER_NEW_INTERVAL = 0;
int CNT_ACCEPTED_USER_NEW_INTERVAL = 0;
int CNT_CALL_USER_ADD_LEFT = 0;
int CNT_ACCEPTED_USER_ADD_LEFT = 0;
int CNT_CALL_USER_REMOVE_LEFT = 0;
int CNT_ACCEPTED_USER_REMOVE_LEFT = 0;
int CNT_CALL_USER_ADD_RIGHT = 0;
int CNT_ACCEPTED_USER_ADD_RIGHT = 0;
int CNT_CALL_USER_REMOVE_RIGHT = 0;
int CNT_ACCEPTED_USER_REMOVE_RIGHT = 0;
int CNT_CALL_USER_DO_CROP = 0;
int CNT_CALL_USER_CROP = 0;
int CNT_ACCEPTED_USER_CROP = 0;
int CNT_CALL_USER_SWAP = 0;
int CNT_ACCEPTED_USER_SWAP = 0;

int THEORY_MAX_SCORE = 1e9;

int cnt_edges[12][12];
int cnt_good_edges[12][12];